#!/usr/bin/python
# vim: set expandtab ts=2 sw=2:

import logging
import MySQLdb
import sys
from config import config

logger = logging.getLogger("get_client_ver")

def get_client_ver(defect, svconn):
  svcursor = svconn.cursor()
  try:
    svcursor.execute("""select hdr_ver from sv_defect where def_id=%s""", (defect,))

    row = svcursor.fetchone()
    if row != None:
      client_ver = row[0]

    if svcursor.fetchone() != None:
      raise RuntimeError('too many results for latest event query')

    return client_ver
  except Exception as err:
    logger.warning('fail get client version err:%s' %err)
    raise err
  finally:
    svcursor.close()

def make_connection(user, host, password, dbname):
  logger.debug('make db connection %s@%s/%s' %(user, host, dbname))
  conn = MySQLdb.connect(user=user, host=host, passwd=password, db=dbname)
  return conn

def setup_logger():
  logging.basicConfig(level=logging.INFO)

if __name__ == '__main__':
  if len(sys.argv) != 2:
    print("usage: %s [defect_num]" %(sys.argv[0]))
    sys.exit(1)

  setup_logger()

  try:
    # TODO get a config file to pull the database information
    svconn = make_connection('aerofs_sv_ro', config["sv_database"], config["aerofs_sv_ro_password"], 'aerofs_sv')
    defect = sys.argv[1]

    logger.debug('get client version for defect:%s' %defect)
    client_ver = get_client_ver(defect, svconn)
    print('%s' %client_ver)
  except:
    logger.error('cannot connect to db')
